#!/bin/bash

# Get the path to me
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source $SCRIPT_DIR/.env

# Send the "next" command to mpv
echo '{ "command": ["playlist-next"] }' | socat - "$SOCKET" > /dev/null
