#!/bin/bash

# Get the path to me
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source $SCRIPT_DIR/.env
source $SCRIPT_DIR/audio-device

# Ensure volume is at the target level and unmuted
amixer -q -c "$AUDIO_CARD" sset "$MIXER_CONTROL" $DEFAULT_VOLUME% unmute -M > /dev/null 2>&1

# Send "pause" command to mpv
echo '{ "command": ["cycle", "pause"] }' | socat - "$SOCKET" > /dev/null
