#!/bin/bash

# Get the path to me
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source $SCRIPT_DIR/.env
source $SCRIPT_DIR/audio-device

# Get paused status
PAUSED=$(echo '{ "command": ["get_property", "pause"] }' | socat - "$SOCKET" | jq '.data')

if [ "$PAUSED" = "true" ]; then
    #amixer -q -c "$AUDIO_CARD" sset "$MIXER_CONTROL" 0% unmute -M > /dev/null 2>&1
    bb-fade in 1
else
    echo '{ "command": ["cycle", "pause"] }' | socat - "$SOCKET" > /dev/null
fi
