#!/bin/bash

# Get the path to me
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source $SCRIPT_DIR/.env

log() {
    # If no arguments are passed to the function, do nothing
    [[ -z "$1" ]] && return

    local message="$@"
    local timestamp=$(date "+%Y-%m-%d %H:%M:%S")

    # 1. Print to Terminal
    #echo "$timestamp $message"

    # 2. Append to Log File
    echo "$timestamp $message" >> "$LOGFILE"
}
